EdgeCut/Entities/Product.cs
namespace EdgeCut.Entities
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public decimal Price { get; set; }
    }
}

EdgeCut/Areas/AdminArea/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace EdgeCut.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EdgeCut/Areas/AdminArea/Controllers/ProductController.cs
using EdgeCut.DAL;
using EdgeCut.Entities;
using Microsoft.AspNetCore.Mvc;

namespace EdgeCut.Areas.AdminArea.Controllers
{
    [Area("AdminArea")] 
    public class ProductController : Controller
    {
        private readonly EdgeDbContext _context;

        public ProductController( EdgeDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Product> products = _context.Products.ToList();
            return View(products);
        }
    }
}

EdgeCut/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace EdgeCut.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EdgeCut/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace EdgeCut.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EdgeCut/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace EdgeCut.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EdgeCut/Controllers/FurnitureController.cs
using Microsoft.AspNetCore.Mvc;

namespace EdgeCut.Controllers
{
    public class FurnitureController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EdgeCut/Controllers/HomeController.cs
using EdgeCut.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.IO.Pipelines;
using System.Xml.Linq;

namespace EdgeCut.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


    }

}

EdgeCut/ViewComponents/ProductViewComponent.cs
using EdgeCut.DAL;
using EdgeCut.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.Internal;

namespace EdgeCut.ViewComponents
{
    public class ProductViewComponent : ViewComponent
    {
        private EdgeDbContext _context { get; set; }
        public ProductViewComponent(EdgeDbContext context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke()
        {
            List<Product> products = _context.Products.ToList();
            return View(products);
        }
    }
}

EdgeCut/Areas/AdminArea/Views/Product/Index.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "Index";
}
<div id="page-wrapper" style="background-color:#202020">
    <div id="page-inner" style="background-color:#202020 !important">
<h1 style="color:white">Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr style="color:white">
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
               Image
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr style="color:white">
            <td>
                @item.Name
            </td>
            <td>
                    <img style="width:180px;" src="~/images/@item.Url" alt="">
            </td>
            <td>
                $@item.Price
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>
</div>

EdgeCut/Areas/AdminArea/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin Panel</title>
    <!-- BOOTSTRAP STYLES-->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="~/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- MORRIS CHART STYLES-->
    <link href="~/assets/js/morris/morris-0.4.3.min.css" rel="stylesheet" />
    <!-- CUSTOM STYLES-->
    <link href="~/assets/css/custom.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
</head>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span> 
                </button>
                <a class="navbar-brand" href="index.html" style="font-size:20px;">Best Coder is Kamran</a>
            </div>
            <div style="color: white;
padding: 15px 50px 5px 50px;
float: right;
font-size: 16px;"> Last access : 30 May 2014 &nbsp; <a href="#" class="btn btn-danger square-btn-adjust">Logout</a>
            </div>
        </nav>
        <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li class="text-center">
                        <img src="~/assets/img/WhatsApp Image 2024-06-14 at 19.15.51_88f8d77e.jpg" style="border-radius:50%" class="user-image img-responsive" />
                    </li>


                    <li>
                        <a class="active-menu" asp-area="AdminArea" asp-controller="Home" asp-action="Index"><i class="fa fa-dashboard fa-3x"></i> Home</a>
                    </li>
                    <li>
                        <a href="ui.html"><i class="fa fa-desktop fa-3x"></i> UI Elements</a>
                    </li>
                    <li>
                        <a href="tab-panel.html"><i class="fa fa-qrcode fa-3x"></i> Tabs & Panels</a>
                    </li>
                    <li>
                        <a href="chart.html"><i class="fa fa-bar-chart-o fa-3x"></i> Morris Charts</a>
                    </li>
                    <li>
                        <a asp-area="AdminArea" asp-controller="Product" asp-action="Index"><i class="fa fa-table fa-3x"></i> Table Examples</a>
                    </li>
                    <li>
                        <a href="form.html"><i class="fa fa-edit fa-3x"></i> Forms </a>
                    </li>


                    <li>
                        <a href="#"><i class="fa fa-sitemap fa-3x"></i> Multi-Level Dropdown<span
                                class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="#">Second Level Link</a>
                            </li>
                            <li>
                                <a href="#">Second Level Link</a>
                            </li>
                            <li>
                                <a href="#">Second Level Link<span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>

                                </ul>

                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="blank.html"><i class="fa fa-square-o fa-3x"></i> Blank Page</a>
                    </li>
                </ul>

            </div>

        </nav>
        @RenderBody()
            
    </div>
    
</body>
</html>

EdgeCut/Views/About/Index.cshtml
@{
    ViewData["Title"] = "About Page";
}


@Html.Partial("_AboutPartial")
@Html.Partial("_EndPartial")

EdgeCut/Views/Blog/Index.cshtml
@{
    ViewData["Title"] = "Blog Page";
}
@Html.Partial("_BlogPartial")
@Html.Partial("_EndPartial")

EdgeCut/Views/Contact/Index.cshtml
@{
    ViewData["Title"] = "Contact Page";
}

@Html.Partial("_ContactPartial")
@Html.Partial("_EndPartial")

EdgeCut/Views/Furniture/Index.cshtml
@{
    ViewData["Title"] = "Furniture Page";
}

<section class="furniture_section layout_padding">
    <div class="container">
        <div class="heading_container">
            <h2>
                Our Furniture
            </h2>
            <p>
                which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't an
            </p>
        </div>
        <div class="row">
            @await Component.InvokeAsync("Product");
        </div>
    </div>
</section>


@Html.Partial("_EndPartial")

EdgeCut/Views/Home/Index.cshtml
@using EdgeCut.Entities
@{
    ViewData["Title"] = "Home Page";
}
<section class="furniture_section layout_padding">
    <div class="container">
        <div class="heading_container">
            <h2>
                Our Furniture
            </h2>
            <p>
                which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't an
            </p>
        </div>
        <div class="row">
            @await Component.InvokeAsync("Product");
            @* @Html.Partial("_ProductPartial") *@
            @* <partial name="_ProductPartial" /> *@
        </div>
    </div>
</section>

@Html.Partial("_AboutPartial")

 @Html.Partial("_BlogPartial")

@Html.Partial("_TestimonialPartial")
@Html.Partial("_ContactPartial")
@Html.Partial("_EndPartial")

EdgeCut/Views/Shared/Components/Product/Default.cshtml
@using EdgeCut.Entities
@model List<Product>

@foreach (Product product in Model)
{
    <div class="col-md-6 col-lg-4">
        <div class="box">
            <div class="img-box">
                <img src="~/images/@product.Url" alt="">
            </div>
            <div class="detail-box">
                <h5>
                    @product.Name
                </h5>
                <div class="price_box">
                    <h6 class="price_heading">
                        <span>$</span> @product.Price
                    </h6>
                    <a href="">
                        Buy Now
                    </a>
                </div>
            </div>
        </div>
    </div>
}

EdgeCut/Views/Shared/_AboutPartial.cshtml
<section class="about_section layout_padding long_section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="img-box">
                    <img src="~/images/about-img.png" alt="">
                </div>
            </div>
            <div class="col-md-6">
                <div class="detail-box">
                    <div class="heading_container">
                        <h2>
                            About Us
                        </h2>
                    </div>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti dolorem eum consequuntur ipsam repellat dolor soluta aliquid laborum, eius odit consectetur vel quasi in quidem, eveniet ab est corporis tempore.
                    </p>
                    <a href="">
                        Read More
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

EdgeCut/Views/Shared/_BlogPartial.cshtml
<section class="blog_section layout_padding">
    <div class="container">
        <div class="heading_container">
            <h2>
                Latest Blog
            </h2>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-4 mx-auto">
                <div class="box">
                    <div class="img-box">
                        <img src="~/images/b1.jpg" alt="">
                    </div>
                    <div class="detail-box">
                        <h5>
                            Look even slightly believable. If you are
                        </h5>
                        <p>
                            alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
                        </p>
                        <a href="">
                            Read More
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 mx-auto">
                <div class="box">
                    <div class="img-box">
                        <img src="~/images/b2.jpg" alt="">
                    </div>
                    <div class="detail-box">
                        <h5>
                            Anything embarrassing hidden in the middle
                        </h5>
                        <p>
                            alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
                        </p>
                        <a href="">
                            Read More
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 mx-auto">
                <div class="box">
                    <div class="img-box">
                        <img src="~/images/b3.jpg" alt="">
                    </div>
                    <div class="detail-box">
                        <h5>
                            Molestias magni natus dolores odio commodi. Quaerat!
                        </h5>
                        <p>
                            alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
                        </p>
                        <a href="">
                            Read More
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

EdgeCut/Views/Shared/_ContactPartial.cshtml
<section class="contact_section  long_section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="form_container">
                    <div class="heading_container">
                        <h2>
                            Contact Us
                        </h2>
                    </div>
                    <form action="">
                        <div>
                            <input type="text" placeholder="Your Name" />
                        </div>
                        <div>
                            <input type="text" placeholder="Phone Number" />
                        </div>
                        <div>
                            <input type="email" placeholder="Email" />
                        </div>
                        <div>
                            <input type="text" class="message-box" placeholder="Message" />
                        </div>
                        <div class="btn_box">
                            <button>
                                SEND
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-6">
                <div class="map_container">
                    <div class="map">
                        <div id="googleMap"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

EdgeCut/Views/Shared/_EndPartial.cshtml
<section class="info_section long_section">

    <div class="container">
        <div class="contact_nav">
            <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                    Call : +01 123455678990
                </span>
            </a>
            <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                    Email : demo@gmail.com
                </span>
            </a>
            <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                    Location
                </span>
            </a>
        </div>

        <div class="info_top ">
            <div class="row ">
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <div class="info_links">
                        <h4>
                            QUICK LINKS
                        </h4>
                        <div class="info_links_menu">
                            <a class="" href="index.html">Home <span class="sr-only">(current)</span></a>
                            <a class="" href="about.html"> About</a>
                            <a class="" href="furniture.html">Furniture</a>
                            <a class="" href="blog.html">Blog</a>
                            <a class="" href="contact.html">Contact Us</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3 mx-auto">
                    <div class="info_post">
                        <h5>
                            INSTAGRAM FEEDS
                        </h5>
                        <div class="post_box">
                            <div class="img-box">
                                <img src="~/images/f1.png" alt="">
                            </div>
                            <div class="img-box">
                                <img src="~/images/f2.png" alt="">
                            </div>
                            <div class="img-box">
                                <img src="~/images/f3.png" alt="">
                            </div>
                            <div class="img-box">
                                <img src="~/images/f4.png" alt="">
                            </div>
                            <div class="img-box">
                                <img src="~/images/f5.png" alt="">
                            </div>
                            <div class="img-box">
                                <img src="~/images/f6.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="info_form">
                        <h4>
                            SIGN UP TO OUR NEWSLETTER
                        </h4>
                        <form action="">
                            <input type="text" placeholder="Enter Your Email" />
                            <button type="submit">
                                Subscribe
                            </button>
                        </form>
                        <div class="social_box">
                            <a href="">
                                <i class="fa fa-facebook" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-twitter" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-linkedin" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-instagram" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

EdgeCut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <link rel="icon" href="~/images/fevicon.png" type="image/gif" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>@ViewData["Title"]</title>


    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet" />

    <!-- font awesome style -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/css/responsive.css" rel="stylesheet" />

</head>

<body>

    <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section long_section px-0">
            <nav class="navbar navbar-expand-lg custom_nav-container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <span>
                        Edgecut
                    </span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class=""> </span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
                        <ul class="navbar-nav  ">
                            <li class="nav-item active">
                                <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="About" asp-action="Index"> About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Furniture" asp-action="Index">Furnitures</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Blog" asp-action="Index">Blog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Contact" asp-action="Index">Contact Us</a>
                            </li>
                        </ul>
                    </div>
                    <div class="quote_btn-container">
                        <a href="">
                            <span>
                                Login
                            </span>
                            <i class="fa fa-user" aria-hidden="true"></i>
                        </a>
                        <form class="form-inline">
                            <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </nav>
        </header>
        <!-- end header section -->
        <!-- slider section -->
        <section class="slider_section long_section">
            <div id="customCarousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="container ">
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="detail-box">
                                        <h1>
                                            For All Your <br>
                                            Furniture Needs
                                        </h1>
                                        <p>
                                            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus quidem maiores perspiciatis, illo maxime voluptatem a itaque suscipit.
                                        </p>
                                        <div class="btn-box">
                                            <a asp-controller="Contact" asp-action="Index" class="btn1">
                                                Contact Us
                                            </a>
                                            <a asp-controller="About" asp-action="Index" class="btn2">
                                                About Us
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-7">
                                    <div class="img-box">
                                        <img src="~/images/slider-img.png" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="container ">
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="detail-box">
                                        <h1>
                                            For All Your <br>
                                            Furniture Needs
                                        </h1>
                                        <p>
                                            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus quidem maiores perspiciatis, illo maxime voluptatem a itaque suscipit.
                                        </p>
                                        <div class="btn-box">
                                            <a asp-controller="Contact" asp-action="Index" class="btn1">
                                                Contact Us
                                            </a>
                                            <a asp-controller="About" asp-action="Index" class="btn2">
                                                About Us
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-7">
                                    <div class="img-box">
                                        <img src="~/images/slider-img.png" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="container ">
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="detail-box">
                                        <h1>
                                            For All Your <br>
                                            Furniture Needs
                                        </h1>
                                        <p>
                                            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus quidem maiores perspiciatis, illo maxime voluptatem a itaque suscipit.
                                        </p>
                                        <div class="btn-box">
                                            <a asp-controller="Contact" asp-action="Index" class="btn1">
                                                Contact Us
                                            </a>
                                            <a asp-controller="About" asp-action="Index" class="btn2">
                                                About Us
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-7">
                                    <div class="img-box">
                                        <img src="~/images/slider-img.png" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <ol class="carousel-indicators">
                    <li data-target="#customCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#customCarousel" data-slide-to="1"></li>
                    <li data-target="#customCarousel" data-slide-to="2"></li>
                </ol>
            </div>
        </section>
        <!-- end slider section -->
    </div>

    @RenderBody();
    <!-- footer section -->
    <footer class="footer_section">
        <div class="container">
            <p>
                &copy; <span id="displayYear"></span> All Rights Reserved By
                <a href="https://html.design/">Free Html Templates</a>
            </p>
        </div>
    </footer>
    <!-- footer section -->
    <!-- jQery -->
    <script src="~/js/jquery-3.4.1.min.js"></script>
    <!-- bootstrap js -->
    <script src="~/js/bootstrap.js"></script>
    <!-- custom js -->
    <script src="~/js/custom.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
    <!-- End Google Map -->

</body>

</html>